theme: jekyll-theme-minimal
title: Keerati's Personal website
description: Developer with extensive experience providing in-depth and widely knowledge in engineering, research, result, interpretation and reporting activities. Proﬁcient in Python, C/C++, Linux, Git and robot control software such as ROS. With 9 years of experience and education in engineering major to make an immediate contribution. Fast adaptation to new challenge and surrounding.
logo: /assets/img/pic.jpg
